version: '3.3'

# servicios a ejecutar
services:

  # MySQL 
  db:
    image: mysql:8.0.31
    container_name: db
    environment:
      - MYSQL_DATABASE=cyship
      - MYSQL_USER=cyship
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db

  # Gitbook
  gitbook:
    image: gitbook
    build: 
      context: .gitbook
      dockerfile: Dockerfile
    container_name: gitbook
    volumes:
      - ./docs:/docs
    ports:
      - 4000:4000
      - 35729:35729
    expose:
      - 4000 
    entrypoint: "tail -f /dev/null" 
    restart: always  
